version: "3"

services:
  web:
    build: ./web
    ports: ["5100:5100"]
    container_name: pandas_flask-api
    links: 
      - database
  database:
    build: ./database
    container_name: pandas_mongodb
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24